# Qt
SET(QT_MIN_VERSION "4.8.0")
FIND_PACKAGE(Qt4 REQUIRED)
SET(QT_USE_QTOPENGL TRUE)
SET(QT_USE_QTGUI TRUE)
SET(QT_USE_QTXML TRUE) # For QDomDoc support
SET(QT_USE_PHONON TRUE) # For Phonon sound support
INCLUDE(${QT_USE_FILE})
IF(QT_FOUND)
  MESSAGE(STATUS "Found Qt includes at ${QT4_INCLUDE_DIR} and libs at ${QT_LIBRARIES}")
ENDIF()

IF(QT_PHONON_FOUND)
  ADD_DEFINITIONS(-DQT_PHONON_FOUND)
ENDIF()

