# Qt 5
FIND_PACKAGE(Qt5Core REQUIRED)
FIND_PACKAGE(Qt5Widgets REQUIRED)
FIND_PACKAGE(Qt5OpenGL REQUIRED)
FIND_PACKAGE(Qt5Gui REQUIRED)
SET(CMAKE_AUTOMOC ON)
IF(QT_FOUND)
  MESSAGE(STATUS "Found Qt includes at ${QT5_INCLUDE_DIR} and libs at ${QT_LIBRARIES}")
ENDIF()

